#!/bin/bash

if [ -e "$(dirname $0)/common.sh" ]; then
    source $(dirname $0)/common.sh
elif [ -e "$(dirname $0)/../common/common.sh" ]; then
    source $(dirname $0)/../common/common.sh
fi

mount_nfs() {
    local host=$1
    local exportDir=$2
    local mountDir=$3
    local opts=$4
    local error

    if [ "$(ismounted $mountDir)" == 0 ]; then
        mkdir -p $mountDir

        get_host_process_pid
        local cmd="nsenter -t ${TARGET_PID} -n mount"
        if [ ! -z "$opts" ]; then
            cmd="$cmd -o $opts"
        fi
        cmd="$cmd $host:$exportDir $mountDir"

        error=`$cmd 2>&1`
        if [ $? -ne 0 ]; then
            print_error "Failed $cmd"
        fi
    fi
}

unmount_nfs() {
    local mountDir="$1"

    if [ $(ismounted "$mountDir") == 1 ] ; then
        error=`umount "$mountDir" 2>&1`
        if [ $? -ne 0 ]; then
            print_error "Failed umount $mountDir: $error"
        fi
    fi

    if [ ! "$(ls -A $mountDir)" ]; then
        rm -rf "$mountDir"
    fi
}

init() {
    print_success
}

tmp_dir() {
    echo "/tmp/$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w5 | head -n1)"
}

################################################################################
# These functions are called by the volume plugin framework (or Rancher)
################################################################################

create() {
    # if user supplies pool=false, do nothing
    if [ "${OPTS[pool]}" == "false" ]; then
        print_success
        exit 0
    fi

    if [ -z "${OPTS[name]}" ]; then
        print_error "name is required"
    fi

    # default configuration
    local host="$DEFAULT_HOST"
    local exportDir="$DEFAULT_EXPORT"
    local opts="$DEFAULT_MOUNT_OPTS"
    local name="${OPTS[name]}"
    local mountDir="$(tmp_dir)"

    # if host/export are set, switch to driver_opts
    if [ ! -z "${OPTS[host]}" ] && [ ! -z "${OPTS[export]}" ]; then
        host="${OPTS[host]}"
        exportDir="${OPTS[export]}"
        opts="${OPTS[mntOptions]}"
    fi

    # create sub-directory using name parameter to represent volume
    mount_nfs "$host" "$exportDir" "$mountDir" "$opts"
    local subDir="$mountDir/$name"
    local created=0
    if [ ! -d "${subDir}" ]; then
        mkdir -p "${subDir}"
        created=1
    fi
    unmount_nfs "${mountDir}"

    if [ "${created}" == 1 ]; then
        print_options pool true name ${OPTS[name]}
    else
        print_success
    fi
}

attach() {
    print_not_supported
}

mountdest() {
    # default configuration
    local host="$DEFAULT_HOST"
    local exportDir="$DEFAULT_EXPORT"
    local opts="$DEFAULT_MOUNT_OPTS"
    local name="${OPTS[name]}"
    local mountDir="$MNT_DEST"

    # if host/export are set, switch to driver_opts
    if [ ! -z "${OPTS[host]}" ] && [ ! -z "${OPTS[export]}" ]; then
        host="${OPTS[host]}"
        exportDir="${OPTS[export]}"
        opts="${OPTS[mntOptions]}"
    fi

    # if pooling is enabled, alter export to point to subdirectory
    if [ "${OPTS[pool]}" != "false" ]; then
        exportDir="$exportDir/$name"
    fi

    mount_nfs "$host" "$exportDir" "$mountDir" "$opts"
    print_success
}

detach() {
    print_not_supported
}

unmount() {
    unmount_nfs "$MNT_DEST"
    print_success
}

delete() {
    # default configuration
    local host="$DEFAULT_HOST"
    local exportDir="$DEFAULT_EXPORT"
    local opts="$DEFAULT_MOUNT_OPTS"
    local name="${OPTS[name]}"
    local mountDir="$(tmp_dir)"

    # if host/export are set, switch to driver_opts
    if [ ! -z "${OPTS[host]}" ] && [ ! -z "${OPTS[export]}" ]; then
        host="${OPTS[host]}"
        exportDir="${OPTS[export]}"
        opts="${OPTS[mntOptions]}"
    fi

    # if pooling is enabled, delete the subdirectory, otherwise delete all data
    mount_nfs "$host" "$exportDir" "$mountDir" "$opts"
    if [ ! -z "${OPTS[pool]}" ]; then
        rm -rf "$mountDir/$name"
    else
        rm -rf "$mountDir/*"
    fi
    unmount_nfs "${mountDir}"

    print_success
}

# Every script must call main as such
main "$@"
