#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/../package

TAG=${TAG:-${IMAGE_VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if [ ! -e ../bin/storage ]; then
    ../scripts/build
fi

> ../dist/images

cp ../bin/storage .
for i in */Dockerfile; do
    BASE=$(dirname $i)
    IMAGE=${REPO}/storage-${BASE}:${TAG}
    docker build -f $i -t ${IMAGE} .
    if [ "$BASE" != "example" ]; then
        echo ${IMAGE} >> ../dist/images
    fi
    echo Built ${IMAGE}
done

