#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/../package

TAG=${TAG:-${IMAGE_VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if [ ! -e ../bin/storage ]; then
    ../scripts/build
fi

> ../dist/images
for i in *; do
    cp ../bin/storage $i
    cd $i
    IMAGE=${REPO}/storage-${i}:${TAG}
    docker build -t ${IMAGE} .
    cd ..
    echo ${IMAGE} >> ../dist/images
    echo Built ${IMAGE}
done

